version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.25
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: mysqld --innodb_use_native_aio=0
    ports:
      - "3306:3306"

  api:
    build:
      context: ./rails
    volumes:
      - ./rails/api:/api
      - api_tmp:/api/tmp
      - public-data:/api/public
      - log-data:/var/log/nginx
    command: sh launch.sh
    environment:
      - API_DATABASE_PASSWORD=password
    #   - RUBY_YJIT_ENABLE=1
    #   - ENVIRONMENT=loacal
    #   - AWS_ACCESS_KEY_ID=dummy
    #   - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - db
      # - localstack

  nginx:
    build:
      context: ./nginx 
    ports:
      - "8080:8080"
    depends_on:
      - api
    volumes:
      - api_tmp:/api/tmp
      - public-data:/api/public
    # networks:
    #   default:
    #     aliases: 
    #       - local-myapp-test.s3-ap-northeast-1.localstack

  # localstack:
  #   image: localstack/localstack
  #   container_name: localstack
  #   ports:
  #     - 4566:4566
  #   environment:
  #     - DEFAULT_REGION=ap-northeast-1
  #     - SERVICES=s3
  #     - DATA_DIR=${DATA_DIR- }
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - ./localstack:/docker-entrypoint-initaws.d
  
  # swagger-ui:
  #   build: ./swagger-ui
  #   volumes:
  #     - ./swagger-ui:/swagger-ui
  #   environment:
  #     - SWAGGER_JSON=/swagger-ui/myapp-api.yaml
  #     - BASE_URL=/swagger-ui
  #   ports:
  #     - "10081:8080"

volumes:
  api_tmp:
    driver: local
  public-data:
  log-data:
    driver: local
  mysql_data:
    driver: local

# networks:
#   default:
#     name: myapp-api